<a href="https://colab.research.google.com/github/antonellafontanetto/DataScience/blob/main/N5_Curso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [4]:
#Importar numpy
import numpy as np

In [ ]:
#Ejercicio1

In [5]:
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

1.1 Crear un arreglo de ceros de longitud 10

In [6]:
import numpy as np


In [8]:
array_cero=np.zeros(10)
print(array_cero)
len (array_cero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


10

In [ ]:
#ejercicio2

In [9]:
array_diez=np.zeros(10)
array_diez[5]=10
print(array_diez)

[ 0.  0.  0.  0.  0. 10.  0.  0.  0.  0.]


In [ ]:
#ejercicio3

In [10]:
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
#ejercicio4

In [13]:
array_8_10=np.arange(9).reshape(3,3)
print(array_8_10)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#ejercicio5

In [14]:
array_100=np.random.rand(100)
print(array_100)

[0.35666203 0.23754554 0.83225121 0.35440512 0.89080737 0.07240532
 0.41280426 0.55989821 0.69676253 0.71533193 0.75544069 0.21380031
 0.39216902 0.19015692 0.86178334 0.14760699 0.37735123 0.59973611
 0.24388411 0.33526563 0.01221762 0.26539061 0.0538112  0.5215735
 0.5525693  0.55721839 0.94039643 0.72485237 0.76592675 0.11317361
 0.87411071 0.25150273 0.19100925 0.8615142  0.87082076 0.26892422
 0.19337604 0.15664488 0.09145284 0.68060828 0.29107065 0.69490131
 0.99054877 0.27579539 0.44616317 0.58460245 0.31335303 0.04176485
 0.20073309 0.78434188 0.91122346 0.8511269  0.90464852 0.71152943
 0.68270899 0.29043176 0.26126352 0.33229179 0.86887752 0.22886462
 0.38146443 0.40150218 0.09404648 0.25093489 0.98182329 0.23375013
 0.17033798 0.25059116 0.27763842 0.76732426 0.94573076 0.55142543
 0.01006271 0.83740889 0.99081913 0.62546438 0.62677952 0.75894952
 0.36774881 0.48928578 0.88016274 0.02905775 0.9530614  0.0990229
 0.96535187 0.07912059 0.33641091 0.4473245  0.74103717 0.031766

In [15]:
array_media=np.mean(array_100)
print(array_media)
array_varianza=np.var(array_100)
print(array_varianza)

0.4924444089095528
0.08971984960579082


In [ ]:
#ejercicio6

In [18]:
array_100_sum=np.sum(array_100)/[len(array_100)]
print(array_100_sum)

[0.49244441]


In [ ]:
#ejercicio 7

In [17]:
array_100_varianza=np.sum((array_100-np.mean(array_100))**2)/[len(array_100)]
print(array_100_varianza)

[0.08971985]


In [ ]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn.

In [19]:
#Crear un array de números aleatorios usando np.random.randn.
array_aletorio=np.random.rand(5)
print(array_aletorio)

[0.23075772 0.83551864 0.75517014 0.76331966 0.22587176]
